
services:
  backend:
    image: prarthanaaa1234/todolist-backend:latest
    # platform: linux/amd64
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    image: prarthanaaa1234/todolist-frontend:latest
    # platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend